<a href="https://colab.research.google.com/github/joshuaarmy/numpy-tutorial/blob/main/numpy_tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np


In [2]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [8]:
b = np.array([[1.2,2.3,3.5],[5.7,6.1,7.3]])
print(b)

[[1.2 2.3 3.5]
 [5.7 6.1 7.3]]


In [9]:
a.ndim


1

In [10]:
b.ndim

2